const tagToCuisineMapping = {
  // Bakery
  dessert: "Bakery",
  "ice cream": "Bakery",
  yogurt: "Bakery",
  "frozen dessert": "Bakery",
  "dairy product": "Bakery",
  cake: "Bakery",
  pastry: "Bakery",
  sugar: "Bakery",
  strawberry: "Bakery",
  chocolate: "Bakery",
  baked: "Bakery",
  cupcake: "Bakery",
  icing: "Bakery",
  syrup: "Bakery",
  mint: "Bakery",
  bread: "Bakery",
  cookies: "Bakery",
  muffin: "Bakery",
  donut: "Bakery",
  croissant: "Bakery",
  pie: "Bakery",
  tart: "Bakery",
  brownie: "Bakery",
  frosting: "Bakery",
  eclair: "Bakery",

  // American
  food: "American",
  sweet: "American",
  delicious: "American",
  snack: "American",
  tasty: "American",
  fresh: "American",
  meal: "American",
  treat: "American",
  diet: "American",
  gourmet: "American",
  plate: "American",
  breakfast: "American",
  nutrition: "American",
  eat: "American",
  cup: "American",
  dinner: "American",
  colorful: "American",
  lunch: "American",
  refreshment: "American",
  party: "American",
  nobody: "American",
  closeup: "American",
  cuisine: "American",
  celebration: "American",
  flavor: "American",
  birthday: "American",
  juicy: "American",
  dish: "American",
  leaf: "American",
  grill: "American",
  steak: "American",
  burger: "American",
  fries: "American",
  "hot dog": "American",
  sandwich: "American",
  bbq: "American",
  ribs: "American",
  wings: "American",

  // Asian
  asian: "Asian",
  noodle: "Asian",
  sushi: "Asian",
  dumpling: "Asian",
  ramen: "Asian",
  wok: "Asian",
  rice: "Asian",
  "stir fry": "Asian",
  "spring roll": "Asian",
  tempura: "Asian",
  "soy sauce": "Asian",
  kimchi: "Asian",
  pho: "Asian",
  "pad thai": "Asian",
  teriyaki: "Asian",
  sashimi: "Asian",
  bento: "Asian",
  curry: "Asian",

  // BBQ
  bbq: "BBQ",
  grill: "BBQ",
  ribs: "BBQ",
  brisket: "BBQ",
  "pulled pork": "BBQ",
  smoked: "BBQ",
  barbecue: "BBQ",
  sausage: "BBQ",
  skewer: "BBQ",
  jerk: "BBQ",

  // Bakery
  cake: "Bakery",
  pastry: "Bakery",
  bread: "Bakery",
  donut: "Bakery",
  croissant: "Bakery",
  pie: "Bakery",
  muffin: "Bakery",
  cookie: "Bakery",

  // Belgian
  waffle: "Belgian",
  "moules frites": "Belgian",
  beer: "Belgian",
  frites: "Belgian",
  chocolate: "Belgian",
  speculoos: "Belgian",
  stoofvlees: "Belgian",
  omelette: "Belgian",

  // Bengali
  bharta: "Bengali",
  "macher jhol": "Bengali",
  sandesh: "Bengali",
  rasgulla: "Bengali",
  "shorshe ilish": "Bengali",
  "chingri malai curry": "Bengali",

  // Indian (for similar tags)
  curry: "Indian",
  naan: "Indian",
  samosa: "Indian",
  biryani: "Indian",
  dal: "Indian",
  paneer: "Indian",
  chapati: "Indian",
  raita: "Indian",
  kebab: "Indian",
  chutney: "Indian",

  // Japanese
  sushi: "Japanese",
  ramen: "Japanese",
  tempura: "Japanese",
  sashimi: "Japanese",
  teriyaki: "Japanese",
  udon: "Japanese",
  miso: "Japanese",
  yakitori: "Japanese",
  takoyaki: "Japanese",
  dashi: "Japanese",

  // Korean
  kimchi: "Korean",
  bulgogi: "Korean",
  bibimbap: "Korean",
  kimbap: "Korean",
  galbi: "Korean",
  japchae: "Korean",
  tteokbokki: "Korean",
  samgyeopsal: "Korean",

  // Mediterranean
  hummus: "Mediterranean",
  falafel: "Mediterranean",
  gyros: "Mediterranean",
  shawarma: "Mediterranean",
  tabbouleh: "Mediterranean",
  pita: "Mediterranean",
  tzatziki: "Mediterranean",
  moussaka: "Mediterranean",
  souvlaki: "Mediterranean",

  // Mexican
  taco: "Mexican",
  burrito: "Mexican",
  nachos: "Mexican",
  quesadilla: "Mexican",
  enchilada: "Mexican",
  salsa: "Mexican",
  guacamole: "Mexican",
  fajitas: "Mexican",
  churros: "Mexican",
  tamale: "Mexican",

  // Persian
  kebab: "Persian",
  shawarma: "Persian",
  "ghormeh sabzi": "Persian",
  fesenjan: "Persian",
  "kashk-e-bademjan": "Persian",
  "saffron rice": "Persian",
  dolmeh: "Persian",
  "ash reshteh": "Persian",
  tahdig: "Persian",

  // Thai
  "pad thai": "Thai",
  "green curry": "Thai",
  "tom yum": "Thai",
  "som tam": "Thai",
  "red curry": "Thai",
  "spring roll": "Thai",
  "drunken noodles": "Thai",
  satay: "Thai",
  "mango sticky rice": "Thai",

  // Vietnamese
  pho: "Vietnamese",
  "banh mi": "Vietnamese",
  "spring roll": "Vietnamese",
  "bun cha": "Vietnamese",
  "goi cuon": "Vietnamese",
  "banh xeo": "Vietnamese",
  "com tam": "Vietnamese",
  "bun bo hue": "Vietnamese",
  "cha gio": "Vietnamese",
};

module.exports = tagToCuisineMapping;
